/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'workersNeeded' : IDL.Nat,
  'phone' : IDL.Text,
  'typeOfWork' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markSubmissionRead' : IDL.Func([IDL.Nat], [], []),
  'markSubmissionUnread' : IDL.Func([IDL.Nat], [], []),
  'submitQuery' : IDL.Func([Submission], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'workersNeeded' : IDL.Nat,
    'phone' : IDL.Text,
    'typeOfWork' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markSubmissionRead' : IDL.Func([IDL.Nat], [], []),
    'markSubmissionUnread' : IDL.Func([IDL.Nat], [], []),
    'submitQuery' : IDL.Func([Submission], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };